# Generated by Django 5.2.6 on 2025-09-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_product_how_to_use_product_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
