# Generated by Django 5.2.6 on 2025-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_video_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
